[wokwi]
version = 1
firmware = '.pio/build/esp32/firmware.bin'
elf = '.pio/build/esp32/firmware.elf'

# Dashboard web de l'ESP32 accessible sur ton PC : http://localhost:8183
[[net.forward]]
from = "localhost:8183"
to = "target:80"
