#!/usr/bin/env node
// ============================================================================
//  Firmware signing tool (developer side, Node.js, no dependencies)
//
//    node tools/sign.js keygen   → new ECDSA P-256 key pair
//                                  keys/private.pem (SECRET, never published)
//                                  src/public_key.h (public key, in the bootloader)
//    node tools/sign.js demo     → src/demo_images.h: demo images
//                                  (valid, tampered, old version, buggy)
//
//  The private key NEVER leaves the developer's PC: the bootloader only
//  contains the public key, which can verify but not sign.
// ============================================================================
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const PRIV = path.join(ROOT, 'keys', 'private.pem');
const FW_MAGIC = 0x4d495746, HDR = 128, SIGNED = 64;

const ver = (s) => { const [a, b = 0, c = 0] = s.split('.').map(Number); return (a << 16) | (b << 8) | c; };

/** Builds an image: signed header + payload */
function buildImage({ version, name, descriptor, size = 4096, key, tamper }) {
  // Payload: descriptor readable by the application + pseudo-random "code"
  const payload = Buffer.alloc(size);
  const seed = crypto.createHash('sha256').update(name).digest();
  for (let i = 0; i < size; i++) payload[i] = seed[i % 32] ^ (i * 131 & 0xff);
  Buffer.from(descriptor + '\0').copy(payload, 0);

  const hdr = Buffer.alloc(HDR);
  hdr.writeUInt32LE(FW_MAGIC, 0);
  hdr.writeUInt16LE(1, 4);
  hdr.writeUInt16LE(0, 6);
  hdr.writeUInt32LE(ver(version), 8);
  hdr.writeUInt32LE(size, 12);
  crypto.createHash('sha256').update(payload).digest().copy(hdr, 16);
  Buffer.from(name.slice(0, 15)).copy(hdr, 48);
  const sig = crypto.sign('sha256', hdr.subarray(0, SIGNED), { key, dsaEncoding: 'ieee-p1363' });
  sig.copy(hdr, 64);
  const img = Buffer.concat([hdr, payload]);
  if (tamper) tamper(img);
  return img;
}

function cArray(name, buf) {
  const lines = [];
  for (let i = 0; i < buf.length; i += 16) lines.push('  ' + [...buf.subarray(i, i + 16)].map((b) => '0x' + b.toString(16).padStart(2, '0')).join(', ') + ',');
  return `static const uint8_t ${name}[${buf.length}] = {\n${lines.join('\n')}\n};\n`;
}

function keygen() {
  const { privateKey, publicKey } = crypto.generateKeyPairSync('ec', { namedCurve: 'P-256' });
  fs.mkdirSync(path.dirname(PRIV), { recursive: true });
  fs.writeFileSync(PRIV, privateKey.export({ type: 'pkcs8', format: 'pem' }), { mode: 0o600 });
  const jwk = publicKey.export({ format: 'jwk' });
  const raw = Buffer.concat([Buffer.from([4]), Buffer.from(jwk.x, 'base64url'), Buffer.from(jwk.y, 'base64url')]);
  fs.writeFileSync(path.join(ROOT, 'src', 'public_key.h'),
    '// Developer ECDSA P-256 public key (generated by tools/sign.js keygen).\n' +
    '// Public: it can VERIFY a signature, not create one.\n#pragma once\n#include <stdint.h>\n' +
    cArray('FW_PUBLIC_KEY', raw));
  console.log('✅ keys created: keys/private.pem (secret) and src/public_key.h');
}

function demo() {
  if (!fs.existsSync(PRIV)) keygen();
  const key = crypto.createPrivateKey(fs.readFileSync(PRIV));
  const attacker = crypto.generateKeyPairSync('ec', { namedCurve: 'P-256' }).privateKey;
  const imgs = {
    IMG_FACTORY_V1: buildImage({ version: '1.0.0', name: 'v1.0 factory', key, descriptor: 'name=v1.0 factory;blink=1000;selftest=ok;msg=Factory firmware' }),
    IMG_V2:         buildImage({ version: '2.0.0', name: 'v2.0', key, descriptor: 'name=v2.0;blink=250;selftest=ok;msg=New version' }),
    IMG_V3_BUGGY:   buildImage({ version: '3.0.0', name: 'v3.0 buggy', key, descriptor: 'name=v3.0 buggy;blink=80;selftest=fail;msg=Version with a bug' }),
    // Attacker #1: modifies the v2 content AND recomputes the hash… but cannot re-sign
    IMG_HACKED:     buildImage({ version: '2.0.0', name: 'v2.0', key, descriptor: 'name=v2.0;blink=250;selftest=ok;msg=New version',
                      tamper: (img) => { Buffer.from('name=HACKED;blink=50;selftest=ok;msg=Backdoor\0').copy(img, HDR);
                                         crypto.createHash('sha256').update(img.subarray(HDR)).digest().copy(img, 16); } }),
    // Attacker #2: signs with THEIR own key
    IMG_WRONG_KEY:  buildImage({ version: '9.0.0', name: 'v9.0', key: attacker, descriptor: 'name=v9.0;blink=50;selftest=ok;msg=Rogue firmware' }),
    // Downgrade: authentic old version (known vulnerabilities)
    IMG_DOWNGRADE:  buildImage({ version: '1.0.0', name: 'v1.0 factory', key, descriptor: 'name=v1.0 factory;blink=1000;selftest=ok;msg=Factory firmware' }),
  };
  let out = '// Generated by tools/sign.js demo — demo images (as if they had been\n' +
            '// downloaded from an update server).\n#pragma once\n#include <stdint.h>\n\n';
  for (const [n, b] of Object.entries(imgs)) out += cArray(n, b) + '\n';
  fs.writeFileSync(path.join(ROOT, 'src', 'demo_images.h'), out);
  console.log('✅ src/demo_images.h:', Object.keys(imgs).join(', '));
}

const cmd = process.argv[2];
if (cmd === 'keygen') keygen();
else if (cmd === 'demo') demo();
else console.log('usage: node tools/sign.js keygen | demo');
